import { run } from './runner'
import './core/logger.test'
import './core/validation.test'
import './core/jwt.test'
import './core/password.test'
import './core/db.test'
import './core/router.test'
import './integration/auth.test'
import './integration/health.test'
import './integration/warehouses.test'
import './integration/orders.test'
import './integration/shipments.test'
import './integration/analytics.test'
import './integration/fraud.test'
import './engines/distance-matrix.test'
import './engines/greedy-init.test'
import './engines/vrp.test'
import './engines/tracking-state-machine.test'
import './engines/exception-detector.test'
import './engines/spatial-index.test'
import './ws/websocket-handshake.test'
import './engines/hungarian.test'
import './engines/demand-forecast.test'
import './engines/time-series.test'
import './engines/percentile.test'
import './engines/fraud-cusum.test'
import './engines/fraud-detector.test'
import './engines/demand-forecast.test'
import './engines/time-series.test'
import './engines/percentile.test'
import './engines/fraud-cusum.test'
import './engines/fraud-detector.test'

run().then(code => process.exit(code)).catch(() => process.exit(1))
